sudo: required

language: c

matrix:
  include:
    - name: "BASE=debian"
      env: BASE=debian TAG=$(date +%Y%m%d)

services:
  - docker

script:
  - docker build -t nathanchance/cbl:${BASE}-${TAG} .
  - docker run --rm -ti nathanchance/cbl:${BASE}-${TAG} clang-8 --version
  - docker run --rm -ti nathanchance/cbl:${BASE}-${TAG} qemu-system-x86_64 --version

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
