sudo: required

language: c

services:
  - docker

matrix:
  include:
    - name: "Development"
      env: LLVM_VERSION=12
    - name: "Stable"
      env: LLVM_VERSION=11

script:
  - make release
  - make check

deploy:
  provider: script
  script: make deploy
  on:
    branch: master

notifications:
  email:
    recipients:
      - natechancellor@gmail.com
    on_success: never
    on_failure: always
