sudo: required

language: c

env:
  global:
    - TAG=$(date +%Y%m%d)

matrix:
  include:
    - name: "Debian"
      env: BASE=debian REPO=clangbuiltlinux/${BASE}

services:
  - docker

script:
  - docker build -t ${REPO}:${TAG} .
  - docker run --rm -ti ${REPO}:${TAG} clang-8 --version
  - docker run --rm -ti ${REPO}:${TAG} qemu-system-x86_64 --version

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
